 /*  FILTRANDO VALORES NULOS 
	USANDO A RELAÇÃO CLIENTE 
	DA NOSSA DATABASE PROJETO
*/

USE PROJETO;

DESC CLIENTE;

/* PROJEÇÃO DE TODOS OS DADOS */
SELECT * FROM CLIENTE;

/* PROCURANDO CLIENTES COM E-MAIL NULOS */
SELECT NOME, SEXO, CPF FROM CLIENTE
WHERE EMAIL IS NULL;

/* PROCURANDO CLIENTES COM E-MAIL NÃO NULOS */
SELECT NOME, SEXO, CPF FROM CLIENTE
WHERE EMAIL IS NOT NULL;

/* USANDO A CLÁSULA 'UPDATE' */
UPDATE CLIENTE
SET EMAIL = 'teste@bd.com'
WHERE NOME = 'CARLA';

/*  USANDO A CLÁSULA 'DELETE' 
	(cuidado ao usar esse comando,
	sempre usar junto com WHERE)
*/

/*  APAGA O CLIENTE ANA 
	(Usar operadores lógicos quando necessário) 
*/
DELETE FROM CLIENTE
SELECT * FROM CLIENTE WHERE NOME = 'ANA';

/* MODELAGEM */

/* PRIMEIRA FORMA NORMAL 

1. TODO CAMPO VETORIZADO SE TORNARÁ OUTRA TABELA;
2. TODO CAMPO MULTIVALORADO(DIVISIVEL) SE TORNARÁ OUTRA TABELA; 
3. TODA TABELA NECESSITA DE PELO MENOS UM CAMPO QUE IDENTIFIQUE
   TODO OS REGISTRO COMO SENDO UNICO. ISSO É O QUE CHAMAMOS DE PRIMARY KEY;
   
   A CHAVE PRIMÁRIA É O QUE IDENTIFICA UMA TUPLA(LINHA DA TABELA)
*/

/*  CARDINALIDADE (E OBRIGATORIEDADE)
	As regras de negócio que definem a cardinalidade.
 */


/* 
	NOSSA REGRA DE NEGÓCIO:
Estamos no início da modelagem para um sistema, e o nosso gestor nos pediu a modelagem 
da tabela de clientes com a seguinte regra de negócios:

ENDERECO - OBRIGATORIO O CADASTRO DE UM ENDERECO (NO MAXIMO 1)
(1,1)
TELEFONE - O CLIENTE NAO É OBRIGADO A INFORMAR TELEFONE
POREM, CASO QUEIRA, ELE PODE INFORMAR MAIS DE UM
(0,n)


    OBRIGATORIEDADE - TRATA SE VAI ACONTECER
	CARDINALIDADE - TRATA DO MÁXIMO QUE VAI ACONTECER
	1ª Coluna é a obrigatoriedade e a 2ª coluna é a cardinalidade
	0 é falso, 1 é verdadeiro e n é mais de um;
	(0 , n)
	(0 , 1)
	(1 , n)
	(1 , 1)		

 */

/* Refazendo o projeto cliente após modelar e usar a primeira forma normal */

CREATE DATABASE COMERCIO;

USE COMERCIO;

/*Vamos criar 3 relações: Cliente, Telefone e Endereco
  IDCLIENTE É A CHAVE PRIMÁRIA, O COMANDO 'AUTO_INCREMENT'
  deixa o banco responsável por incrementar/contar 
  ID_CLIENTE É A NOSSA CHAVE ESTRANGEIRA
*/
CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M','F') NOT NULL,
	CPF VARCHAR(15) UNIQUE,
	EMAIL VARCHAR(50) UNIQUE
);

-- RELACIONAMENTO 0xN
CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('RES', 'COM', 'CEL') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT,
	FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);

-- RELACIONAMENTO 1x1
CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR (40) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE,
	FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);

/*
	ENDERECO: OBRIGATORIO
		CADASTRO DE SOMENTE UM
	
	TELEFONE: NÃO OBRIGATÓRIO
		CADASTRO DE MAIS DE UM (OPCIONAL)
*/

/*
CHAVE ESTRANGEIRA É A CHAVE PRIMARIA DE UMA TABELA
QUE VAI ATÉ A OUTRA TABELA PARA FAZER REFERENCIA ENTRE
REGISTROS */

/* EM RELACIONAMENTO 1 X 1 A CHAVE ESTRANGEIRA FICA NA TABELA MAIS FRACA */

/* EM RELACIONAMENTO 1 X N A CHAVE ESTRANGEIRA FICARA SEMPRE NA
CARDINALIDADE N */

INSERT INTO CLIENTE VALUES (NULL, 'JOAO', 'M', 'JOAO@IG.COM', '76548932104');
INSERT INTO CLIENTE VALUES(NULL,'CARLOS','M','CARLOSA@IG.COM','5464553466');
INSERT INTO CLIENTE VALUES(NULL,'ANA','F','ANA@IG.COM','456545678');
INSERT INTO CLIENTE VALUES(NULL,'CLARA','F',NULL,'5687766856');
INSERT INTO CLIENTE VALUES(NULL,'JORGE','M','JORGE@IG.COM','8756547688');
INSERT INTO CLIENTE VALUES(NULL,'CELIA','M','JCELIA@IG.COM','5767876889');
 
SELECT * FROM CLIENTE;

-- RETORNO DA TABELA CLIENTE
+-----------+--------+------+----------------+-------------+
| IDCLIENTE | NOME   | SEXO | CPF            | EMAIL       |
+-----------+--------+------+----------------+-------------+
|         1 | JOAO   | M    | JOAO@IG.COM    | 76548932104 |
|         2 | CARLOS | M    | CARLOSA@IG.COM | 5464553466  |
|         3 | ANA    | F    | ANA@IG.COM     | 456545678   |
|         4 | CLARA  | F    | NULL           | 5687766856  |
|         5 | JORGE  | M    | JORGE@IG.COM   | 8756547688  |
|         6 | CELIA  | M    | JCELIA@IG.COM  | 5767876889  |
+-----------+--------+------+----------------+-------------+

INSERT INTO ENDERECO VALUES(NULL,'RUA ANTONIO SA','CENTRO','B. HORIZONTE','MG',4);
INSERT INTO ENDERECO VALUES(NULL,'RUA CAPITAO HERMES','CENTRO','RIO DE JANEIRO','RJ',1);
INSERT INTO ENDERECO VALUES(NULL,'RUA PRES VARGAS','JARDINS','SAO PAULO','SP',3);
INSERT INTO ENDERECO VALUES(NULL,'RUA ALFANDEGA','ESTACIO','RIO DE JANEIRO','RJ',2);
INSERT INTO ENDERECO VALUES(NULL,'RUA DO OUVIDOR','FLAMENGO','RIO DE JANEIRO','RJ',6);
INSERT INTO ENDERECO VALUES(NULL,'RUA URUGUAIANA','CENTRO','VITORIA','ES',5);

SELECT * FROM ENDERECO;

-- RETORNO DA TABELA ENDERECO (1,1)
+------------+--------------------+----------+----------------+--------+------------+
| IDENDERECO | RUA                | BAIRRO   | CIDADE         | ESTADO | ID_CLIENTE |
+------------+--------------------+----------+----------------+--------+------------+
|          1 | RUA ANTONIO SA     | CENTRO   | B. HORIZONTE   | MG     |          4 |
|          2 | RUA CAPITAO HERMES | CENTRO   | RIO DE JANEIRO | RJ     |          1 |
|          3 | RUA PRES VARGAS    | JARDINS  | SAO PAULO      | SP     |          3 |
|          4 | RUA ALFANDEGA      | ESTACIO  | RIO DE JANEIRO | RJ     |          2 |
|          5 | RUA DO OUVIDOR     | FLAMENGO | RIO DE JANEIRO | RJ     |          6 |
|          6 | RUA URUGUAIANA     | CENTRO   | VITORIA        | ES     |          5 |
+------------+--------------------+----------+----------------+--------+------------+

INSERT INTO TELEFONE VALUES(NULL,'CEL','78458743',5);
INSERT INTO TELEFONE VALUES(NULL,'RES','56576876',5);
INSERT INTO TELEFONE VALUES(NULL,'CEL','87866896',1);
INSERT INTO TELEFONE VALUES(NULL,'COM','54768899',2);
INSERT INTO TELEFONE VALUES(NULL,'RES','99667587',1);
INSERT INTO TELEFONE VALUES(NULL,'CEL','78989765',3);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99766676',3);
INSERT INTO TELEFONE VALUES(NULL,'COM','66687899',1);
INSERT INTO TELEFONE VALUES(NULL,'RES','89986668',5);
INSERT INTO TELEFONE VALUES(NULL,'CEL','88687909',2);

SELECT * FROM TELEFONE;

-- RETORNO DA TABELA TELEFONE (0,N)
+------------+------+----------+------------+
| IDTELEFONE | TIPO | NUMERO   | ID_CLIENTE |
+------------+------+----------+------------+
|          1 | CEL  | 78458743 |          5 |
|          2 | RES  | 56576876 |          5 |
|          3 | CEL  | 87866896 |          1 |
|          4 | COM  | 54768899 |          2 |
|          5 | RES  | 99667587 |          1 |
|          6 | CEL  | 78989765 |          3 |
|          7 | CEL  | 99766676 |          3 |
|          8 | COM  | 66687899 |          1 |
|          9 | RES  | 89986668 |          5 |
|         10 | CEL  | 88687909 |          2 |
+------------+------+----------+------------+

