/* Modelagem básica 
   Infomrações primárias do cliente */

CLIENTE

NOME - CARACTER(50)
CPF - NUMER(11)
EMAIL - CARACTER(30)
CELULAR - NUMER(11)
ENDERECO - CARACTER(100)
SEXO - (1)

/* PROCESSOS DE MODELAGEM */

/* FASE 01 E FASE 02 - AD ADM DE DADOS */ 
MODELAGEM CONCEITUAL: RASCUNHO
MODELAGEM LÓGICA: SOFTWARE DE MODELAGEM

-- FASE 03  - DBA / AD 

MODELAGEM FÍSICA: SCRIPTS DE BANCO DE DADOS

/* INICIANDO A MODELAGEM FÍSICA */

/* CRIANDO O BANCO DE DADOS */

CREATE DATABASE PROJETO;	/* Query OK, 1 row affected (0.01 sec) */

/* CONECTANDO AO BANCO DE DADOS 
   O COMANDO "USE" SEMPRE É UTILIZADO
   APÓS FECHAR O SGBD E ABRIR AGAIN.
*/

USE PROJETO;				/* Database changed */

/* CRIANDO TABELA DE CLIENTES */

CREATE TABLE CLIENTE(
	NOME  VARCHAR(50),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11), 
	TELEFONE VARCHAR(20),
	ENDERECO VARCHAR(100)
);							/*Query OK*/

/* VERIFICANDO TABELAS DO NOSSO BANCO */

SHOW TABLES;				/* Tabela cliente exibida */

/* DESCOBRINDO ESTRUTURA DE UMA TABELA */

DESC CLIENTE;

/* FORMA 01 - OMITINDO AS COLUNAS */

INSERT INTO CLIENTE VALUES('JOAO','M','JOAO@GMAIL.COM',988638273,'22923110','MAIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES('CELIA','F','CELIA@GMAIL.COM',541521456,'25078869','RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES('JORGE','M',NULL,885755896,'58748895','OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');

/* FORMA 02 - COLOCANDO AS COLUNAS */

INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('LILIAN','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','947785696',887774856);

/* FORMA 03 - INSERT COMPACTO - SOMENTE MYSQL */

INSERT INTO CLIENTE VALUES('ANA','F','ANA@GLOBO.COM',85548962,'548556985','PRES ANTONIO CARLOS - CENTRO - SAO PAULO - SP'),
                          ('CARLA','F','CARLA@TERATI.COM.BR',7745828,'66587458','SAMUEL SILVA - CENTRO - BELO HORIZONTE - MG');
				
/* EXEMPLOS DE ERRO */				
INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('CLARA','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','883665843',99999999999);

INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('HIA','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','883665843',22222222222);
